### ISSUE TITLE
Any credential with SSO and public key credentials available for user asks for password in specific circumstances for SSH

### ISSUE THREAD

**Issue by SheaSmith** [warp-tech/warpgate#972]
If you have the following conditions:

1. A user with an SSH public key and SSO configured.
2. SSH is set to use 'Any credential'
3. You attempt to login to SSH without the specified public key being installed (and therefore would expect to be prompted for a keyboard interactive login)

Then you will be actually asked for a password, rather than the keyboard interactive flow:
![image](https://github.com/warp-tech/warpgate/assets/51303984/5ebb4e55-ddc7-44ed-b405-c1db8e9036c0)

Warpgate config for the user:
![image](https://github.com/warp-tech/warpgate/assets/51303984/e831c780-6638-431a-bc00-9dabb6867d6d)

Happy to provide any relevant logs or config if that helps.

**Comment by theMackabu** [comment]
https://github.com/warp-tech/warpgate/issues/946#issuecomment-2087785920 comment moved here

**Comment by Eugeny** [comment]
I haven't been able to reproduce this but I suspect that your client might have a different preferred auth method order than mine. Anyway, the fix makes sure that password auth won't be offered when the user has no password.

**Comment by SheaSmith** [comment]
Thanks - I'm not seeing the issue with the password any more with the latest update. However, it doesn't seem like I'm prompted with keyboard interactive when I deny public key access (I'm using the 1Password SSH agent, which allows for public key access to be denied) with this config:
![image](https://github.com/user-attachments/assets/3a92e79e-38c7-4341-a053-3b54a3bbebdb)

Here's the logs for `sftp -v` when connecting:
```
sftp -v -P 2222 -o User=shea:<site name> <host>
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to <host> [192.168.1.201] port 2222.
debug1: Connection established.
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_rsa type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ecdsa_sk type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ed25519_sk type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ed25519_sk-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.6
debug1: Remote protocol version 2.0, remote software version russh_0.44.0
debug1: compat_banner: no match: russh_0.44.0
debug1: Authenticating to <host>:2222 as 'shea:<site name>'
debug1: load_hostkeys: fopen C:\\Users\\SheaSmith/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:xVWOC/rHefNW0i0G9IurVCPc+REGuAcoDmQtyMULzbE
debug1: load_hostkeys: fopen C:\\Users\\SheaSmith/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: Host '[<host>]:2222' is known and matches the ED25519 host key.
debug1: Found key in C:\\Users\\SheaSmith/.ssh/known_hosts:17
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: Test Key ED25519 SHA256:dEqsKHcXY8v3cQ7Xp8uUg2P20TktUfdQES3m2iJORLI agent
debug1: Will attempt key: <another key> Access ED25519 SHA256:rTqMg0ntdf7sd0jUBty2dEwLT/ILeZjCLNByMi9+qO4 agent
debug1: Will attempt key: <yet another key> ED25519 SHA256:bVkq0AbK8MRrV1kTDM/SwtPp4ed1Y5t3FR4UtCme9bM agent
debug1: Will attempt key: <fourth key> key ED25519 SHA256:S9GgTPUpwbHHNTFARPtY7eSkKzYG5GU57kfpB7LTM/A agent
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_rsa
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_dsa
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_ecdsa_sk
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_ed25519_sk
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,rsa-sha2-256,rsa-sha2-512,ssh-rsa>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: password,publickey,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key: Test Key ED25519 SHA256:dEqsKHcXY8v3cQ7Xp8uUg2P20TktUfdQES3m2iJORLI agent
debug1: Server accepts key: Test Key ED25519 SHA256:dEqsKHcXY8v3cQ7Xp8uUg2P20TktUfdQES3m2iJORLI agent
sign_and_send_pubkey: signing failed for ED25519 "Test Key" from agent: agent refused operation
debug1: Offering public key: <another key> Access ED25519 SHA256:rTqMg0ntdf7sd0jUBty2dEwLT/ILeZjCLNByMi9+qO4 agent
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: <yet another key> ED25519 SHA256:bVkq0AbK8MRrV1kTDM/SwtPp4ed1Y5t3FR4UtCme9bM agent
debug1: Authentications that can continue: publickey
debug1: Offering public key: <fourth key> key ED25519 SHA256:S9GgTPUpwbHHNTFARPtY7eSkKzYG5GU57kfpB7LTM/A agent
debug1: Authentications that can continue: publickey
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_rsa
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_dsa
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_ecdsa
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_ecdsa_sk
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_ed25519
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_ed25519_sk
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_xmss
debug1: No more authentication methods to try.
shea:<site name>@<host>: Permission denied (publickey).
```

When I change it so that both SSO and public key are required in the config, e.g.:
![image](https://github.com/user-attachments/assets/ae3854e0-0970-423d-9cb3-33ce4b95f0b1)

I am prompted for the keyboard interactive login after denying the public key access, but it hangs after asking for approval (which I imagine is somewhat expected, since I would've thought that configuration requires both public key and keyboard interactive to login):
```
sftp -v -P 2222 -o User=shea:<site name> <host>
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to <host> [192.168.1.201] port 2222.
debug1: Connection established.
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_rsa type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ecdsa_sk type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ed25519_sk type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_ed25519_sk-cert type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\SheaSmith/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.6
debug1: Remote protocol version 2.0, remote software version russh_0.44.0
debug1: compat_banner: no match: russh_0.44.0
debug1: Authenticating to <host>:2222 as 'shea:<site name>'
debug1: load_hostkeys: fopen C:\\Users\\SheaSmith/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:xVWOC/rHefNW0i0G9IurVCPc+REGuAcoDmQtyMULzbE
debug1: load_hostkeys: fopen C:\\Users\\SheaSmith/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: Host '[<host>]:2222' is known and matches the ED25519 host key.
debug1: Found key in C:\\Users\\SheaSmith/.ssh/known_hosts:17
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: Test Key ED25519 SHA256:dEqsKHcXY8v3cQ7Xp8uUg2P20TktUfdQES3m2iJORLI agent
debug1: Will attempt key: <another key> ED25519 SHA256:rTqMg0ntdf7sd0jUBty2dEwLT/ILeZjCLNByMi9+qO4 agent
debug1: Will attempt key: <yet another key> ED25519 SHA256:bVkq0AbK8MRrV1kTDM/SwtPp4ed1Y5t3FR4UtCme9bM agent
debug1: Will attempt key: <fourth key> ED25519 SHA256:S9GgTPUpwbHHNTFARPtY7eSkKzYG5GU57kfpB7LTM/A agent
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_rsa
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_dsa
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_ecdsa_sk
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_ed25519_sk
debug1: Will attempt key: C:\\Users\\SheaSmith/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,rsa-sha2-256,rsa-sha2-512,ssh-rsa>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: password,publickey,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key: Test Key ED25519 SHA256:dEqsKHcXY8v3cQ7Xp8uUg2P20TktUfdQES3m2iJORLI agent
debug1: Server accepts key: Test Key ED25519 SHA256:dEqsKHcXY8v3cQ7Xp8uUg2P20TktUfdQES3m2iJORLI agent
sign_and_send_pubkey: signing failed for ED25519 "Test Key" from agent: agent refused operation
debug1: Offering public key: <another key> ED25519 SHA256:rTqMg0ntdf7sd0jUBty2dEwLT/ILeZjCLNByMi9+qO4 agent
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key: <yet another key> ED25519 SHA256:bVkq0AbK8MRrV1kTDM/SwtPp4ed1Y5t3FR4UtCme9bM agent
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: Offering public key: <fourth key> ED25519 SHA256:S9GgTPUpwbHHNTFARPtY7eSkKzYG5GU57kfpB7LTM/A agent
debug1: Authentications that can continue: publickey,keyboard-interactive
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_rsa
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_dsa
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_ecdsa
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_ecdsa_sk
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_ed25519
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_ed25519_sk
debug1: Trying private key: C:\\Users\\SheaSmith/.ssh/id_xmss
debug1: Next authentication method: keyboard-interactive
Warpgate authentication
-----------------------------------------------------------------------
Warpgate authentication: please open the following URL in your browser:
https://<host>/@warpgate#/login/b0bc6009-6e90-49cf-a7b8-f58c41b40c6e

Make sure you're seeing this security key: 1 E 8 B
-----------------------------------------------------------------------

(shea:<site name>@<host>) Press Enter when done:
```

**Comment by theMackabu** [comment]
@SheaSmith same issue, able to reproduce

**Comment by M0ustach3** [comment]
Hi,

I have a really similar issue where, If you setup a user via SSO and do not configure anything else and you let the default Auth method "Any credential" in the SSH configuration, you will actually be prompted for a password instead of having an SSO link to authenticate via Web.

![Image](https://github.com/user-attachments/assets/0785e110-242e-4390-a1ee-336fbb0b2be9)

![Image](https://github.com/user-attachments/assets/68f670b5-ebd4-4908-9186-dd6e294aeefd)


However, If you uncheck "Any credential" and check the only available option "In-browser auth" for the user, it does actually work and prompts for a Link for web SSO.

![Image](https://github.com/user-attachments/assets/6836a191-35b2-4807-bd8c-452b87c893da)

![Image](https://github.com/user-attachments/assets/7d5f8e7e-912a-4613-945f-32ed3b6df077)

Cheers,

**Comment by M0ustach3** [comment]
Any news on this issue ? It's been more that one year since that bug appears

**Comment by Eugeny** [comment]
Should be fixed now

**Comment by joseluisgonzalezca** [comment]
After making some tests, I came to the conclusion that the issue is not yet resolved because I'm able to reproduce @M0ustach3 scenario with the latest available version. My feedback:

* First issue: I think there's a TYPO in this line. As far as I understand, the negation mark `!` is missing!

https://github.com/warp-tech/warpgate/blob/972880a6bd99a8012811dd249470f5edc98de969/warpgate-protocol-ssh/src/server/session.rs#L1504-L1507

* Second issue: I think these lines introduced in commit https://github.com/warp-tech/warpgate/commit/6cb156df1fc83cf68dd84bd36441659f7e332434 broke the original solution. That filter is being applied for all protocols. As a solution, that code block may be moved to `is_sufficient` method for `AllCredentialsPolicy` in `policy.rs` file.

https://github.com/warp-tech/warpgate/blob/972880a6bd99a8012811dd249470f5edc98de969/warpgate-core/src/config_providers/db.rs#L127-L137

Could you provide some feedback about this? Is there another workaround @Eugeny ?

If you need any more details or you want me to open another issue, feel free to reach me out.

Thank you! :)

**Comment by Eugeny** [comment]
The first bit of code is correct - it pushes web approval to the end of the auth method list if it's already present but doesn't add it otherwise.

In the second case, you're right and it could be improved by only filtering out web approval if there are other methods available.
IMO web approval should not be automatically included in the "any credential" policy if there are actual credentials set up for the user and it just leads to more confusion

**Comment by joseluisgonzalezca** [comment]
Thank you for your quick reply :)

> The first bit of code is correct - it pushes web approval to the end of the auth method list if it's already present but doesn't add it otherwise.

You are totally right.  The name `push` misleaded me. `russh` library docs are concise about the method behaviour. Sorry about that.

> In the second case, you're right and it could be improved by only filtering out web approval if there are other methods available. IMO web approval should not be automatically included in the "any credential" policy if there are actual credentials set up for the user and it just leads to more confusion

I understand your point. Your proposal looks fine to me. I'll try to submit a PR with the fix later today.

**Comment by matbgn** [comment]
Sorry to bother you guys, but I'm still experiencing some issue here.

Whenever I check "Any credential" or only "In-Browser auth" I don't get the URL link displayed. 

![Image](https://github.com/user-attachments/assets/2db9963d-d432-4a64-a2ad-2ed2bbc2435e)

But if I have the Warpgate interface open, I can approve the request and type enter and login successfully. Any clue about the config for keyboard interactive login that I should adapt, or is it still related to this issue?

![Image](https://github.com/user-attachments/assets/865dec60-7596-44ac-9355-9ef0b229a844)

**Comment by joseluisgonzalezca** [comment]
Hi @matbgn!

Could you provide some more info about your current setup? I can try to replicate your case in my local test environment if you provide me:

- **Version**: Are you using the nightly version? Take into account that the "official release" of v.0.14.1 does not provide the fix.
- **User auth methods**: Do you have SSO and password for your current user?
- **SSH target auth policy**: Do you Any enabled or In-Browser?

Thank you!

**Comment by matbgn** [comment]
Hi @joseluisgonzalezca thank you for reaching out. Of course here the requested information:

- Version: docker v0.15.0-beta.1-modified
- User auth methods: only SSO no password for this user
- SSH target only In-Browser

Don't hesitate if you need anything more, BTW I put the ssh verbose log here:

```
$ ssh 'matbgn:bqn-vmg-102@IP_REDACTED' -p 2222 -v
OpenSSH_9.6p1 Ubuntu-3ubuntu13.12, OpenSSL 3.0.13 30 Jan 2024
debug1: Reading configuration data /home/matbgn/.ssh/config
debug1: Reading configuration data /home/matbgn/Dev/itpark/config/ssh/shared-config
debug1: /home/matbgn/.ssh/config line 4: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to IP_REDACTED [IP_REDACTED] port 2222.
debug1: Connection established.
debug1: identity file /home/matbgn/.ssh/id_rsa type -1
debug1: identity file /home/matbgn/.ssh/id_rsa-cert type -1
debug1: identity file /home/matbgn/.ssh/id_ecdsa type -1
debug1: identity file /home/matbgn/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/matbgn/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/matbgn/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/matbgn/.ssh/id_ed25519 type -1
debug1: identity file /home/matbgn/.ssh/id_ed25519-cert type -1
debug1: identity file /home/matbgn/.ssh/id_ed25519_sk type -1
debug1: identity file /home/matbgn/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/matbgn/.ssh/id_xmss type -1
debug1: identity file /home/matbgn/.ssh/id_xmss-cert type -1
debug1: identity file /home/matbgn/.ssh/id_dsa type -1
debug1: identity file /home/matbgn/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.12
debug1: Remote protocol version 2.0, remote software version russh_0.53.0
debug1: compat_banner: no match: russh_0.53.0
debug1: Authenticating to IP_REDACTED:2222 as 'matbgn:bqn-vmg-102'
debug1: load_hostkeys: fopen /home/matbgn/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-rsa SHA256:REDACTED
debug1: load_hostkeys: fopen /home/matbgn/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '[IP_REDACTED]:2222' is known and matches the RSA host key.
debug1: Found key in /home/matbgn/.ssh/known_hosts:187
debug1: ssh_packet_send2_wrapped: resetting send seqnr 3
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: Sending SSH2_MSG_EXT_INFO
debug1: expecting SSH2_MSG_NEWKEYS
debug1: ssh_packet_read_poll2: resetting read seqnr 3
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_ext_info_client_parse: server-sig-algs=<ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: get_agent_identities: bound agent to hostkey
debug1: get_agent_identities: agent returned 5 keys
debug1: Will attempt key: /home/matbgn/.ssh/id_rsa 
debug1: Will attempt key: /home/matbgn/.ssh/id_ecdsa 
debug1: Will attempt key: /home/matbgn/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/matbgn/.ssh/id_ed25519 
debug1: Will attempt key: /home/matbgn/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/matbgn/.ssh/id_xmss 
debug1: Will attempt key: /home/matbgn/.ssh/id_dsa 
debug1: Trying private key: /home/matbgn/.ssh/id_rsa
debug1: Trying private key: /home/matbgn/.ssh/id_ecdsa
debug1: Trying private key: /home/matbgn/.ssh/id_ecdsa_sk
debug1: Trying private key: /home/matbgn/.ssh/id_ed25519
debug1: Trying private key: /home/matbgn/.ssh/id_ed25519_sk
debug1: Trying private key: /home/matbgn/.ssh/id_xmss
debug1: Trying private key: /home/matbgn/.ssh/id_dsa
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: password
matbgn:bqn-vmg-102@IP_REDACTED's password: 
```

**Comment by joseluisgonzalezca** [comment]
Hi again @matbgn!

I'm sorry but I'm not able to reproduce your issue. Here is my current scenario in case you see something different:

**User config:**

<img width="908" alt="Image" src="https://github.com/user-attachments/assets/0c9a26a2-de98-44ef-a1ee-d0b19cf98520" />

**Example target config:**

<img width="814" alt="Image" src="https://github.com/user-attachments/assets/5cad1400-393c-47c5-a760-0c81525b9fa4" />

**SSH output: (All working as expected)**

```shell
jlgonzalez@Joses-MacBook-Air ~ % ssh 'jlgonzalez:TEST@bastion.test' -p 2222
   pgate authentication                                                                                                                                         ----------------------------------------------------------------------

Warpgate authentication: please open the following URL in your browser:
https://bastion.test/@warpgate#/login/256937e6-04bb-4b46-bc2c-349ac4e51e70

Make sure you're seeing this security key: 6 9 8 B
-----------------------------------------------------------------------

(jlgonzalez:TEST@bastion.test) Press Enter when done:
 Warpgate  Selected target: TEST
 Warpgate  Host key (ssh-rsa): AAAAB3NzaC1yc2EAAAADAQABAAABAQDLEhE2sLxqAzZqo2Vjp4Jt/iC2pDcSr9MTNcNK28X1mdJa5V4TUY7yfNIz9VHwpzIcTUE8JTy+rAYm7uudCztCKOW7kudQaEDcqHptOYRfeaIG4jzoCrfpratnpVTd+wb0E2trZre8KTMa4Y1RBCfwkjZj012KS6t15fy3McZu5PCvGd3v+0pCyhv39uUTFm91FMoyyfJEKQKZ0gHEDJxmJ7euDhYoX6J2ExZK8n3PG2oeV047sRfIJJwPl4wWql53P9dmmUY0aAVPTPTiznC8qbwv2mt9oyNix5avIeft2VluipHT84IGO88MMbrPrXU8k24ZKP2KTYbqlhI9w0NZ

 Warpgate  There is no trusted ssh-rsa key for this host.
 Warpgate  Trust this key? (y/n)

 ✓ Warpgate connected
y
```
